version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          command: |
            echo hello
      - run:
          name: Running tests
          command: |
            node -p 'os.version()'
