version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor:
      name: "win/default"
    steps:
      - checkout
      - run:
          command: |
            echo hello
      - run:
          name: Running tests
          shell: cmd
          command: |
            signtool
