version: 2.1
jobs:
  build:
    docker:
      - image: docker.io/library/alpine:3.16
    steps:
      - checkout
      - run:
          command: |
            echo hello
      - run:
          name: Running tests
          command: |
            node -p 'os.version()'
