version: 2.1

commands:
  dependencies:
    steps:
      - run:
          name: Install automake
          command: brew install automake

      - run:
          name: Install coreutils
          command: brew install coreutils

      - run:
          name: Install libtool
          command: brew install libtool

      - run:
          name: Install pkg-config
          command: brew install pkg-config

      - run:
          name: Clone openssl
          command: git clone --depth 1 -b openssl-3.0.8+quic https://github.com/quictls/openssl

      - run:
          name: Clone nghttp3
          command: git clone --depth 1 -b v0.9.0 https://github.com/ngtcp2/nghttp3

      - run:
          name: Clone ngtcp2
          command: git clone --depth 1 -b v0.13.1 https://github.com/ngtcp2/ngtcp2

      - run:
          name: Clone curl
          command: git clone --depth 1 -b curl-7_88_1 https://github.com/curl/curl

  build:
    steps:
      - run:
          name: Build openssl
          command: |
            cd openssl
            ./config --prefix=$(realpath $PWD/../install) --libdir=$(realpath $PWD/../install/lib)
            make install_sw

      - run:
          name: Build nghttp3
          command: |
            cd nghttp3
            autoreconf -fi
            ./configure --prefix=$(realpath $PWD/../install) PKG_CONFIG_PATH="$(realpath $PWD/../install/lib/pkgconfig)" --enable-lib-only
            make install

      - run:
          name: Build ngtcp2
          command: |
            cd ngtcp2
            autoreconf -fi
            ./configure --prefix=$(realpath $PWD/../install) PKG_CONFIG_PATH="$(realpath $PWD/../install/lib/pkgconfig)" --enable-lib-only --with-openssl
            make install

      - run:
          name: Build curl
          command: |
            cd curl
            autoreconf -fi
            ./configure --prefix=$(realpath $PWD/../install) --with-openssl=$(realpath $PWD/../install) PKG_CONFIG_PATH="$(realpath $PWD/../install/lib/pkgconfig)" LDFLAGS="-Wl,-rpath,$(realpath $PWD/../install/lib)" --with-ngtcp2="$(realpath $PWD/../install)" --enable-warnings --enable-werror --enable-debug --with-test-nghttpx="$(realpath $PWD/../install/bin/nghttpx)"
            make CFLAGS="-mmacosx-version-min=10.15 -Wno-deprecated-declarations" install

  test:
    steps:
      - run:
          name: Curl version
          command: install/bin/curl --version

      - run:
          name: Send regular HTTP request
          command: install/bin/curl https://www.google.com

      - run:
          name: Send HTTP3 request
          command: install/bin/curl --http3 https://www.google.com

jobs:
  build:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - dependencies
      - build
      - test
