name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: action
      run: |
        icacls README.md
        dir
        icacls README.md /deny "everyone:(D)"
        icacls README.md
        dir
        del README.md
        dir
        dir
        icacls README.md
        icacls README.md /remove:d "everyone"
        icacls README.md
        dir
        del README.md
        dir
