name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: RaisinTen/actions/node-base@use-node-base-in-make-pear-app
      with:
        node-auth-token: ${{ github.token }}
