name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: protect
      run: |
        icacls README.md
        dir
        icacls README.md /deny everyone:(DE,WD,AD)
        icacls README.md
      shell: cmd

    - name: rm-protected
      run: |
        del README.md
        dir
      shell: cmd

    - name: unprotect
      run: |
        dir
        icacls README.md /remove:d everyone
      shell: cmd

    - name: rm-unprotected
      run: |
        del README.md
        dir
      shell: cmd
