name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: lts/*

    - name: Install
      shell: bash
      run: |
        npm ci

    - name: Build
      shell: bash
      run: |
        npm run make:linux-x64
        file out/linux-x64/tests

    - name: Test linux build
      shell: bash
      run: |
        out/linux-x64/tests linux-x64 ./linux app.mjs
        ./linux/tests

    - name: Test macOS build
      shell: bash
      run: |
        out/linux-x64/tests darwin-arm64 ./darwin-arm64 app.mjs
        file darwin-arm64/*

    - name: Build rest
      shell: bash
      run: |
        npm run make:linux-arm64
        file out/linux-arm64/tests

        npm run make:darwin-arm64
        file out/darwin-arm64/tests

        npm run make:darwin-x64
        file out/darwin-x64/tests

        npm run make:win32-arm64
        file out/win32-arm64/tests.exe

        npm run make:win32-x64
        file out/win32-x64/tests.exe
