name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Install choco
      shell: cmd
      run: |
        powershell -Command "iwr -useb get.scoop.sh | iex"
        set PATH=%USERPROFILE%\scoop\shims;%PATH%
        tree %USERPROFILE%\scoop /F /A

    - name: Install choco
      shell: cmd
      run: |
        tree %USERPROFILE%\scoop /F /A
        powershell -Command "scoop install shellcheck"
        tree %USERPROFILE%\scoop /F /A

    - name: Use shellcheck
      shell: cmd
      run: |
        shellcheck -V
