name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2

    - name: Compile program that uses SHGetFolderPath to read the Start menu folder path
      shell: cmd
      run: |
        cl test.c /link Shell32.lib

    - name: Query Start menu folder path from registry
      shell: cmd
      run: |
        reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Start Menu"

    - name: Query Start menu folder descriptions from registry
      shell: cmd
      run: |
        reg query "Software\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions" /v "{625B53C3-AB48-4EC1-BA1F-A1EF4146FC19}"

    - name: Read Start menu folder path using SHGetFolderPath
      shell: cmd
      run: |
        test.exe

    - name: Modify Start menu folder path to another existing folder path in registry
      shell: cmd
      run: |
        reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /t REG_SZ /v "Start Menu" /d "C:\Users\runneradmin\AppData\Roaming\Microsoft\Windows" /f

    - name: Query Start menu folder path from registry
      shell: cmd
      run: |
        reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Start Menu"

    - name: Read Start menu folder path using SHGetFolderPath
      shell: cmd
      run: |
        test.exe

    - name: Modify Start menu folder path to inexistent folder path in registry
      shell: cmd
      run: |
        reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /t REG_SZ /v "Start Menu" /d "lol" /f

    - name: Query Start menu folder path from registry
      shell: cmd
      run: |
        reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Start Menu"

    - name: Read Start menu folder path using SHGetFolderPath
      shell: cmd
      run: |
        test.exe

    - name: Delete Start menu folder path from the registry
      shell: cmd
      run: |
        reg delete "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /f /v "Start Menu"

    - name: Query Start menu folder path from registry
      shell: cmd
      run: |
        reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Start Menu"
      continue-on-error: true

    - name: Read Start menu folder path using SHGetFolderPath
      shell: cmd
      run: |
        test.exe
